"""
Redraw the shop's wallpaper as a seamless SVG.

The room at 240 Lancaster is papered in an Art Deco sunburst — gold on near
black. Measured from a straight-on photograph of it (2026-09-01):

  * The wall is a lattice of thick gold diagonals forming diamonds that are
    very nearly a square stood on its corner — a touch taller than wide.
  * Each diamond holds a fan of thinner rays from its bottom corner. The ray
    tips are evenly spaced along the diamond's two upper edges: six rays a
    side at one-seventh steps, plus a centre ray to the top corner; the
    seventh step is the lattice line itself. So the rays crowd together at
    the top and open out toward the sides, and the widest gap sits against
    the diagonal.
  * The rays are about a hundredth of the diamond's width; the lattice lines
    about twice that. Nothing is filled — no leaf, no solid apex — the rays
    just merge where they meet.
  * The top corner of every diamond is the bottom corner of the one above, so
    each column of fans stacks point to point, and the columns are offset by
    half a diamond.

Rebuilding rather than tiling the photo means it is crisp at any size, weighs
a few kilobytes, and can be tinted to any brass the page needs.

Writes the finished pattern to app/pattern.css as a base64 data URI.
"""

import base64

W = 180.0                  # one diamond, which is also the tile width
H = 190.0                  # a touch taller than wide, as on the wall
SIDE_RAYS = 6              # rays each side of the centre ray
STEPS = SIDE_RAYS + 1      # tip spacing along an upper edge; step 7 is the lattice
RAY_W, LATTICE_W = 1.9, 3.4
GOLD = "#b0873f"


def seg(x1: float, y1: float, x2: float, y2: float) -> str:
    return f'<line x1="{x1:.2f}" y1="{y1:.2f}" x2="{x2:.2f}" y2="{y2:.2f}"/>'


def fan(cx: float, cy: float) -> list[str]:
    """The rays of one diamond, from its bottom corner (cx, cy)."""
    top = (cx, cy - H)
    parts = []
    for k in range(-SIDE_RAYS, SIDE_RAYS + 1):
        f = abs(k) / STEPS
        side = (cx + (W / 2 if k > 0 else -W / 2), cy - H / 2)
        tip = (top[0] + f * (side[0] - top[0]), top[1] + f * (side[1] - top[1]))
        parts.append(seg(cx, cy, *tip))
    return parts


def build() -> str:
    # Every diamond that touches the tile: the one that sits inside it, the
    # two either side (offset half a cell), and the three above whose rays
    # reach down into the tile's top corners. The viewBox clips the rest.
    apexes = [
        (W / 2, H), (0.0, H / 2), (W, H / 2),
        (W / 2, 2 * H), (0.0, 1.5 * H), (W, 1.5 * H),
    ]
    rays: list[str] = []
    for cx, cy in apexes:
        rays += fan(cx, cy)

    # The lattice: the diamond inside the tile, whose four edges continue as
    # the edges of its neighbours. Each segment ends exactly on the tile
    # boundary, where the next tile's segment picks it up on the same line.
    lattice = [
        seg(0, H / 2, W / 2, 0),
        seg(W / 2, 0, W, H / 2),
        seg(W, H / 2, W / 2, H),
        seg(W / 2, H, 0, H / 2),
    ]

    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{W:g}" height="{H:g}" '
        f'viewBox="0 0 {W:g} {H:g}">'
        f'<g stroke="{GOLD}" fill="none">'
        f'<g stroke-width="{RAY_W}">' + "".join(rays) + "</g>"
        f'<g stroke-width="{LATTICE_W}">' + "".join(lattice) + "</g>"
        "</g></svg>"
    )


def main() -> None:
    svg = build()
    uri = "data:image/svg+xml;base64," + base64.b64encode(svg.encode()).decode()

    css = f"""/* Generated by tools/build-pattern.py — do not edit by hand.
   The Art Deco sunburst from the shop's own wallpaper, redrawn so it stays
   crisp at any size. Applied through .deco, which controls only opacity. */
.deco {{
  background-image: url("{uri}");
  background-repeat: repeat;
  background-size: {W:g}px {H:g}px;
}}
"""
    with open("app/pattern.css", "w") as f:
        f.write(css)
    print(f"svg {len(svg)} B · css {len(css)} B → app/pattern.css")

    with open("/tmp/pattern-preview.html", "w") as f:
        f.write(
            '<body style="margin:0;background:#0b0a09">'
            f'<div style="height:560px;background:url({uri}) repeat;'
            f'background-size:{W:g}px {H:g}px"></div>'
            f'<div style="height:200px;opacity:.06;background:url({uri}) repeat;'
            f'background-size:{W:g}px {H:g}px"></div></body>'
        )


if __name__ == "__main__":
    main()
