"""
Redraw the shop's wallpaper as a seamless SVG.

The room at 240 Lancaster is papered in an Art Deco fan — gold rays on near
black, tessellated so each fan's apex sits between the two fans below it. The
photograph of it is unusable (plastic still on the mirrors, wires on the floor),
but the geometry is simple enough to rebuild: a fan of straight rays from a
point, plus a solid centre leaf, laid on a half-offset grid.

Rebuilding rather than tiling the photo means it is crisp at any size, weighs
about a kilobyte, and can be tinted to any brass the page needs.

Writes the finished pattern to app/pattern.css as a base64 data URI.
"""

import base64
import math

W, ROW = 110.0, 150.0      # one cell: a tall lozenge, as on the wall
H = ROW * 2                # tile holds two rows so the half-offset repeats
RAYS = 13                  # rays per fan
SPREAD = 0.98              # how wide the fan opens, as a fraction of the cell
GOLD = "#b0873f"


def fan(cx: float, cy: float) -> list[str]:
    """One fan: rays from an apex, plus the solid leaf up its middle."""
    parts = []
    for i in range(RAYS):
        t = (i / (RAYS - 1)) * 2 - 1                     # -1 … 1
        # Ray tips trace the lozenge: full height at the centre, half height
        # at the left and right vertices. Straight edges, not a scallop.
        drop = 1.0 - abs(t) * 0.5
        x = cx + t * (W / 2) * SPREAD
        y = cy - ROW * drop
        parts.append(
            f'<line x1="{cx:.2f}" y1="{cy:.2f}" x2="{x:.2f}" y2="{y:.2f}"/>'
        )
    tip, waist = cy - ROW * 0.92, cy - ROW * 0.46
    parts.append(
        f'<path d="M{cx:.2f} {cy:.2f}'
        f'L{cx - 5.2:.2f} {waist:.2f}L{cx:.2f} {tip:.2f}'
        f'L{cx + 5.2:.2f} {waist:.2f}Z" fill="{GOLD}" stroke="none"/>'
    )
    return parts


def build() -> str:
    body: list[str] = []
    # Two rows, the upper offset half a cell from the lower, with the
    # neighbours either side drawn in so the tile repeats without a seam.
    for cx in (0.0, W, -W):
        body += fan(cx, H)          # lower row, apexes on the tile edge
    for cx in (-W / 2, W / 2, W * 1.5):
        body += fan(cx, ROW)        # upper row, offset by half a cell

    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{W:g}" height="{H:g}" '
        f'viewBox="0 0 {W:g} {H:g}">'
        f'<g stroke="{GOLD}" stroke-width="1.6" fill="none" '
        f'stroke-linecap="round">'
        + "".join(body)
        + "</g></svg>"
    )


def main() -> None:
    svg = build()
    uri = "data:image/svg+xml;base64," + base64.b64encode(svg.encode()).decode()

    css = f"""/* Generated by tools/build-pattern.py — do not edit by hand.
   The Art Deco fan from the shop's own wallpaper, redrawn so it stays crisp
   at any size. Applied through .deco, which controls only opacity and scale. */
.deco {{
  background-image: url("{uri}");
  background-repeat: repeat;
  background-size: 110px 300px;
}}
"""
    with open("app/pattern.css", "w") as f:
        f.write(css)
    print(f"svg {len(svg)} B · css {len(css)} B → app/pattern.css")

    with open("/tmp/pattern-preview.html", "w") as f:
        f.write(
            '<body style="margin:0;background:#0b0a09">'
            f'<div style="height:420px;background:url({uri}) repeat;'
            'background-size:110px 300px"></div>'
            f'<div style="height:220px;opacity:.14;background:url({uri}) repeat;'
            'background-size:180px 491px"></div></body>'
        )


if __name__ == "__main__":
    main()
